version: '3'

services:
  db:
    env_file:
      - .env
    image: mysql:8.0
    volumes:
      - ./.sql:/docker-entrypoint-initdb.d:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    platform: linux/x86_64

  web:
    env_file:
      - .env
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./.composer:/var/www/composer
      - ./.wp:/var/www/html
      - ./api:/var/www/html/api
      - ./.env:/var/www/.env
      - ./theme:/var/www/html/wp-content/themes/theme
      - ./plugins:/var/www/html/wp-content/plugins
